---
- name: restart webmin
  ansible.builtin.systemd:
    name: webmin
    state: restarted

- name: restart usermin
  ansible.builtin.systemd:
    name: usermin
    state: restarted

- name: restart ssh
  ansible.builtin.systemd:
    name: ssh
    state: restarted
