version: "3.9"

services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.cloud == true
          - node.labels.leader == true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=1
      - EVENTS=1
      - INFO=1
      - IMAGES=1
      - NETWORKS=1
      - VOLUMES=1
      - PING=1
      - VERSION=1
      - NODES=1
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
      - TZ=${TZ}
    networks:
      - socket_proxy
    logging:
      driver: json-file
      options:
        max-size: "12m"
        max-file: "5"

networks:
  socket_proxy:
    external: true
