# Docker Swarm Discovery Configuration

# For Swarm Service Discovery (Cluster-wide)
my-swarm:
  socket: /var/run/docker.sock
  swarm: true

# For Local Resources Widget (Node Stats)
local:
  socket: /var/run/docker.sock
  swarm: false
