# Global Widgets
# https://gethomepage.dev/latest/configs/widgets/

- search:
    provider: google
    focus: true
    target: _blank

- glances:
    url: http://homepage_glances:61208
    version: 4
    cpu: true
    mem: true
    uptime: true
    disk: /rootfs
    expanded: true
    label: System

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
