---
ceph_monitors: "10.0.70.10,10.0.70.11,10.0.70.12"
cephfs_monitors: "10.0.70.10,10.0.70.11,10.0.70.12"
cephfs_mount_point: "/data/homelab"
cephfs_user: "admin"
# Read from CEPH_SECRET_KEY env var via Doppler in run.sh
cephfs_secret: "{{ ceph_secret_key | default(lookup('env', 'CEPH_SECRET_KEY')) | default('') }}"
cephfs_fs_name: "cephfs-vm"
cephfs_path: "/"

cephfs_mount_options: "name={{ cephfs_user }},secretfile=/etc/ceph/{{ cephfs_user }}.secret,fs={{ cephfs_fs_name }},noatime,_netdev"

cephfs_app_dirs:
  - configs
  - volumes
  - backups
  - docker-data
